version: "3.9"

services:
  openclaw:
    build: .
    container_name: openclaw

    command: >
      sh -c "node openclaw.mjs gateway &
             node openclaw.mjs dashboard &&
             wait"

    ports:
      - "19001:19001"
      - "18789:18789"

    volumes:
      - ./data:/app/data

    restart: unless-stopped